server:
  port: 8080

spring:
  datasource:
    username: admin
    password: Penalead135
    url: jdbc:mysql://branny-bd.cjfcaqzawb8m.us-east-1.rds.amazonaws.com:3306/PruebaTecnica
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 3600000 # 1 hora (3600000 milisegundos)
      max-lifetime: 3600000 # 1 hora (3600000 milisegundos)
      connection-timeout: 30000 # 30 segundos (30000 milisegundos)
      validation-timeout: 5000 # 5 segundos (5000 milisegundos)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true