server:
  port: 8000

spring:
  datasource:
    username: admin
    password: Penalead135
    url: jdbc:mysql://branny-bd.cjfcaqzawb8m.us-east-1.rds.amazonaws.com:3306/PruebaTecnica
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true