server:
  port: 3000

spring:
  datasource:
    username: admin
    password: Penalead135
    url: jdbc:mysql://branny-bd.cjfcaqzawb8m.us-east-1.rds.amazonaws.com:3306/PruebaTecnicaFractal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true